In [ ]:
#hide
#from sidis import *

# *SIDIS* :

> **SI**mple **D**ata **I**nterface**S** , https://noeloikeau.github.io/sidis/

is a Python module for easy data science named after the early American polymath, William James Sidis.

The modules here implement extensive recursion and typecasting beneath the hood in order to eliminate common programming tasks like converting and sorting data in slightly different ways. 

Even for expert python users, the programs here are powerful. Documentation can be found on the respective pages in the docs website above. Here we give a brief overview of some of the main functions.

## Install

**NYI**: `pip install sidis`

## How to use

In [ ]:
import sidis
from sidis import *

C:\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)


## Sorting, converting, accessing complex datastructures

In [ ]:
from sidis import sort, convert

In [ ]:
sort([9,0,1,8,7],by=convert,key=lambda t:len(t[-1])) 

[(9, array([1, 0, 0, 1])),
 (8, array([1, 0, 0, 0])),
 (7, array([1, 1, 1])),
 (0, array([0])),
 (1, array([1]))]

In [ ]:
sort([9,0,1,8,7],by=nbits,sift=lambda t:t[-1]>2)

[(9, 4), (8, 4), (7, 3)]

In [ ]:
from functools import partial
sort([9,0,1,8,7],by=partial(convert,to=hex,astype=int)) 

[(9, '0x9'), (8, '0x8'), (7, '0x7'), (1, '0x1'), (0, '0x0')]

In [ ]:
import networkx as nx
g=nx.DiGraph()
g.add_edges_from([(0,1),(1,2),(2,0)])
g.add_edges_from([(0,0)])
g.in_degree()

InDegreeView({0: 2, 1: 1, 2: 1})

In [ ]:
from sidis import get
get(g,'in_degree',0) #arbitrary access to objects and functions

2

In [ ]:
sort(g.nodes,by=g.in_degree)

[(0, 2), (1, 1), (2, 1)]

In [ ]:
sort(g.nodes,by=g.edges,key=lambda t:len(list(t[-1])))

[(0, OutEdgeDataView([(0, 1), (0, 0)])),
 (1, OutEdgeDataView([(1, 2)])),
 (2, OutEdgeDataView([(2, 0)]))]

In [ ]:
from sidis import give
give(g,'nodes',0,newattr='for fun')
g.nodes[0]['newattr']

'for fun'

In [ ]:
[give(g,'edges',e,weight=np.random.rand(1)) for e in g.edges]
sort(g.edges,'weight')

[array([0.97601752]),
 array([0.86388663]),
 array([0.78046723]),
 array([0.02531015])]

## ... and more!

In [ ]:
from sidis import depth,flatten,inflate,fillar,Template,RNG,cast

In [ ]:
depth({'a':0,'b':{'c':1,'d':3}})

2

In [ ]:
flatten({'a':0,'b':{'c':1,'d':3}})

{'a': 0, 'b,c': 1, 'b,d': 3}

In [ ]:
inflate({'a': 0, 'b,c': 1, 'b,d': 3})

{'a': 0, 'b': {'c': 1, 'd': 3}}

In [ ]:
fillar([[1],[2,3]],fillwith=1000,mask=False)

array([[   1, 1000],
       [   2,    3]])

In [ ]:
Template('''
fill out your _name
and provide {0} ZIP _iter, lambda t: 'embedded iterable functions!'
''',_name='name and information',_iter=range(1))

fill out your name and information
and provide embedded iterable functions! 

In [ ]:
cast((0.1,0.5,2.5),int)

(0, 0, 2)

In [ ]:
rng=RNG(0) #globally stable
rng.random(0,1,shape=(2,2))

array([[0.63696169, 0.26978671],
       [0.04097352, 0.01652764]])

In [ ]:
#hide
refresh()
push(comment='first commit')

TypeError: 'bool' object is not callable